===== Nie ustępowanie pierwszeństwa dla pojazdów uprawnionych do korzystania z buspasów

Pojazdy uprzywilejowane mają wiele problemów z egzekucją pierwszeństwa na buspasach.
W związku z tym należało by zbadać w pierwszej kolejności, w których miejscach problem ten występuje i w jakiej skali.
Następnie na podstawie badania zostanie przeprowadza wizja środowiskowa zakładająca możliwe następujące rozwiązania:
poszerzenie jezdni w celu niezajmowania przez pojazdy nieuprawnione buspasów,
wprowadzenie monitoringu w celu pouczenia lub/i karania kierowców niestosujących się do przepisów,
przeprowadzenie miejscowej kampanii społecznej polegającej na informowaniu użytkowników o prowidłowej metodzie korzystania z buspasów oraz kto jest na nich uprzywilejowany.

Po wdrożeniu jednogo / kilku z proponowanych rozwiązań należałoby powtórzyć badanie w miejscach problematycznych w celu sprawdzenia czy problem został rozwiązany czy potrzeba nowych środków.
W drugiej turze należałoby zbadać podane miejsca pod kątem wprowadzenia nowej sygnalizacji tylko dla pojazdów uprzywilejowanych, 
wprowadzenie fizycznego oddzielenia buspasa od innych pasów (w tym celu należałoby przebudować skrzyżowania na bezkolizyjne o ile to możliwe) oraz znięchecaczy dla innych pojazdów w postaci progów,
przez które pojazdy uprzewilejowane mogą bezproblemowo przejechać ze względu na większy rozstaw osi. 
Jeżeli te metody również nie pomogą, pozostaje przebadanie czy nie istnieje możliwość całkowitej likwidacji buspasów na rzecz innego środka komunikacji (tramwaju, metra) co ostatecznie rozwiąże problem.
Istnieje także możliwość zwiększenia ilości zieleni w mieście.
Koszt rozwiązania rośnie wraz ze stopniem skomplikowania proponowanych metod.

