===== Buspas jest użytkowany przez wiele pojazdów, wiele z nich nie jest do tego uprawnionych

Problem ten jest wysoce podobny do problemu 8-C.2. Zarówno tutaj więc należało by prześledzić miejsce występowania problemów - w tym wypadku trasy autobusu 523. W miejscach stwierdzenia największych problemów należy następnie zrobić badnie środowiskowe na ile możliwe jest implementacja jednego z następujących rozwiązań: Poszerzenia jezdnii aby pojazdy nie musiały zajmować buspasu, kampanii informacyjnej, monitoringu i kar/pouczeń dla osób nieuprawnionych wjeżdżających na buspas. Następnie przetestowanie czy dane rozwiązanie sprawdza się czy potrzeba dalszych kroków. W przypadku nie rozwiązania problemu w powyżej podane sposoby należy zwiększyć środki i poprzeprowadzeniu nowego badania podjąć jeden z następujących kroków: Oddzielenie buspasa od reszty pasów fizycznymi barierarmi w celu uniemożliwienia innym samochodom przejazdu na nie. Wprowadzenie przeszkód na drodzę w postaci progów, które autobusy pokonają bez problemu ze względu na swój rozstaw osi. W przypadku braku sukcesu również tego rozwiązania należy zastanowić się nad sensem buspasa i ewentualnej jego zmiany na inny środek komunikacji.