===== Rozwiązanie przypadku, gdy pieszy obawia się, że nie jest w stanie spokojnie przejść przez całą ulicę, ponieważ światło jest za krótkie

Obawa przed zbyt krótkim czasem światła zielonego występuje głównie na drogach wielopasmowych o dużym natężeniu ruchu. Rozwiązaniem może być stworzenie przejść podziemnych dla ruchliwych ulic. Będąc rozwiązaniem dla ludzi młodych, osoby o ograniczonej mobilności i osoby starsze preferują pokonywanie skrzyżowań jak najkrótszą drogą, zwłaszcza bez konieczności schodzenia/wchodzenia po schodach. Wówczas, jeśli miejsce na to pozwala, można także zastosować wysepki. 

Alternatywnym rozwiązaniem jest, w razie mniejszego natężenia ruchu, analiza drożności skrzyżowania przy wyłączonej sygnalizacji (migające światło żółte) i w razie satysfakcjonujących wyników, całkowite lub częściowe (np. w pewnych godzinach) jej usunięcie.

Rozwiązaniem najbardziej kosztownym jest budowanie tych najbardziej ruchliwych skrzyżowań jako wielopoziomowe, gdzie pieszy porusza się na poziomie ziemi, a samochody w tunelach pod ziemią lub wiaduktach nad ziemią.
