===== Rozwiązanie problemu, gdy pieszy obawia się, że nie jest w stanie spokojnie przejść przez całą ulicę, ponieważ światło jest za krótkie

Obawa przed zbyt krótkim trwaniem światła zielonego występuje głównie na drogach wielopasmowych o dużym natężeniu ruchu.
Rozwiązaniem może być stworzenie przejść podziemnych dla ruchliwych ulic.
Propozycja ta, będąc rozwiązaniem dla ludzi młodych, nie jest korzystna dla osób o ograniczonej mobilności i osób starszych, preferujących pokonywanie skrzyżowań jak najkrótszą drogą, zwłaszcza bez konieczności schodzenia lub wchodzenia po schodach.
Wówczas, jeśli miejsce na to pozwala, można także zastosować wysepki. 

Alternatywnym rozwiązaniem jest, w razie mniejszego natężenia ruchu, analiza drożności skrzyżowania przy wyłączonej sygnalizacji (migające światło żółte) i w razie satysfakcjonujących wyników, całkowite lub częściowe (np. w pewnych godzinach) jej usunięcie.

Rozwiązaniem najbardziej kosztownym jest budowanie tych najbardziej ruchliwych skrzyżowań jako wielopoziomowe, gdzie pieszy porusza się na poziomie ziemi, a samochody w tunelach pod ziemią lub wiaduktach nad ziemią.
