===== Rozwiązanie problemy, gdy pieszy obawia się, że nie zdąży przejść przez ulicę, aby zdążyć na autobus / inny środek transportu czekający po drugiej stronie ulicy w trakcie nadawania zielonego sygnału

Podobnie jak w przypadku przystanków podwójnych, na których kierowcy obu autobusów stojących jednocześnie na przystanku powinni umożliwić przesiadkę, 
tak w przypadku przystanków nieopodal skrzyżowań, kierowcy powinni zaczekać aż piesi pokonają przejście prowadzące do przystanku. 
W tym celu potrzebny jest automatyczny system informowania kierowców bazujący na zliczaniu osób na przejściu idących w danym kierunku.

Inne podejście, wymagające większej aktywności osoby zainteresowanej, bazuje na stworzenej uprzednio aplikacji do planowania przejazdu.
Pozwalałaby ona sprawdzić rozkład, dojazd, położenie pojazdów komunikacji, a także ustalenie preferencji dotyczących korzystania z określonych linii w pewnych godzinach lub jednorazowych ustawień, zgodnie z wyszukiwaną trasą.
W razie zbliżania się do przystanku (co byłoby ustalane według sygnału GPS), na którym jest lub do którego zbliża się pojazd zadanej linii, wysyłana byłaby automatycznie informacja o podróżnym spieszącym się do danego pojazdu.
W zależności od opóźnienia (lub braku) proponowana byłaby odpowiedź kierowcy na takie żądanie, którą mógłby on ręcznie zmienić w przeciągu niewielkiego czasu.
Informacja o wejściu osób do pojazdu byłaby automatyczna.

