===== Przyczyny strachu rowerzysty

[[cyclist_fear_1]]
====== Strach ze względu na samochody
Rowerzysta uważa, że samochody tylko niszczą środowisko.
Dodatkowo byłoby lepiej, gdyby ulice zostały parkami, a cały ruch został przeniesiony na koleje i rowery. 
Jednakże, jako że nie jest w stanie tego zmienić, musi razem z nimi (kierowcami samochodów) uczestniczyć w ruchu drogowym. 
Boi się jednak, że nieodpowiedzialne zachowanie osoby kierującej samochodem spowoduję wypadek. 
Na ten strach mają wpływ następujące składowe:

* strach przed byciem uderzonym przez samochód -- wynika z faktu, że bardzo niewiele osób stosuje się do przepisów związanych z zieloną strzałką. Rowerzysta boi się, że ktoś w niego stuknie i wyląduje on (rowerzysta) w szpitalu;
* strach przed wpadnięciem pod samochód -- jest związany z dynamiką skrętu za "zieloną strzałką". Rowerzysta obawia się, że nie zauważy jadącego samochodu lub ten będzie jechał nieprzepisowo, co sprawi, że spotkają się w pół drogi;

[[cyclist_fear_2]]
====== Strach ze względu na pieszych/rowerzystów
Rowerzysta, który, jak każdy obywatel, sam często jest pieszym uczestnikiem ruchu, a wtedy niezwykle denerwują go rowerzyści.
Boi się, że ktoś kogoś nie zauważy lub też nie zastosuje się do przepisów, przez co wpadną na siebie i ostatecznie wyląduje on (jako pieszy) w szpitalu.
W związku z tym, będąc samemu rowerzystą, wytwarza to u niego następujące lęki:

* strach przed wpadnięciem na innego rowerzystę lub pieszego – jest to związane z dynamiką skrętu.
  Rowerzysta boi się, że może kogoś nie zauważyć i spowodować kolizję.
  Szczególnie mocny jest strach przed wpadnięciem na innego rowerzystę, który będzie nieprzepisowo przejeżdżał przez przejście dla pieszych;
* strach przed byciem posądzonym o nierozważną jazdę -- rowerzysta boi się, że zacznie robić to samo, co denerwuje go jako pieszego (nieświadoma hipokryzja),
  a to wprost przekłada się na strach przed niewypowiedzianym hejtem przez innych uczestników ruchu drogowego lub pieszych.
  Rowerzysta stara się być lubianym i szanowanym obywatelem, w związku z tym ogarnia go strach, że stosując się lub nie stosując się do zielonej strzałki, sprowadzi na siebie niewypowiedziane obelgi i złe myśli innych uczestników;

[[cyclist_fear_3]]
====== Strach ze względu na istnienie manewru skrętu
Rowerzysta uważa, że ze względu na niebezpieczeństwa wyżej wymienione, zielone strzałki tak jak i cały manewr skrętu, powinny zostać zlikwidowane, a ruch rozwiązany taki sposób, aby nie stresować ludzi;

[[cyclist_fear_4]]
====== Strach samej strzałki
Rowerzysta zawsze był indywidualistą, a strzałki kojarzą mu się z nakierowywaniem i przymusami.
W związku z tym, udział w ruchu drogowym powoduje u niego strach, gdyż niewykluczone jest, że będzie musiał podążyć za jakąś strzałką;

[[cyclist_fear_5]]
====== Strach związany z kolorem zielonym
Rowerzysta od zawsze ma złe skojarzenia z kolorem zielonym.
W szkole podstawowej nauczycielka języka polskiego zawsze wystawiała mu oceny niedostateczne do dziennika takim (zielonym) kolorem, co doprowadziło do jego niechęci związanych z tym kolor.
W związku z tym często odwraca głowę od zielonych rzeczy.
Jednak jako uczestnik ruchu drogowego jest on zmuszony na niego patrzeć (światła, strzałka), co wywołuje u niego stres i strach, że z przyczyn od niego niezależnych przeoczy zieloną strzałkę lub jej brak;

[[cyclist_fear_6]]
====== Strach do przepisów
Rowerzysta, do czego nie chce się przyznać, zawalił w młodości egzamin na kartę rowerową.
To doświadczenie wykształciło to u niego lęk, przed nauką przepisów ruchu drogowego (co dodatkowo spowodowało rozwinięcie się lęku przed aresztowaniem oraz testofobii),
dlatego każdorazowe zetknięcie się z nim (nawet tylko poprzez zauważenie samej zielonej strzałki) wywołuje u niego niekontrolowany, paraliżujący strach.
