===== Przyczyny strachu rowerzysty – zielona strzałka:

*	Strach ze względu na samochody – Rowerzysta uważa, że samochody tylko niszczą środowisko a ulicę lepiej aby zostały parkami a cały ruch przenieść na koleje i rowery jednakże, jako że nie jest w stanie tego zmienić, musi razem z nimi uczestniczyć w ruchu drogowym. Boi się jednak, że nieodpowiedzialne zachowanie osoby kierującej samochodem spowoduję wypadek. Na ten strach składają się następujące składowe:
->	Strach przed byciem uderzonym przez samochód – w zawiązku z tym, że bardzo niewiele osób stosuje się do przepisów związanych z zieloną strzałką rowerzysta boi się, że ktoś w niego stuknie i wyląduje on w szpitalu.
->	Strach przed wpadnięciem pod samochód – w związku z dynamiką skrętu za strzałką, Rowerzysta obawia się, że nie zauważy jadącego samochodu lub ten będzie jechał nieprzepisowo i ostatecznie spotkają się w pół drogi.
*	Strach ze względu na pieszych/rowerzystów – Rowerzysta sam często jest pieszym i będąc nim, niezwykle denerwują go rowerzyści – boi się, że ktoś kogoś nie zauważy lub też nie zastosuje się do przepisów, przez co wpadną na siebie i ostatecznie wyląduje on w szpitalu. W związku z tym będąc samemu rowerzystą wytwarza to u niego następujące lęki:
->	Strach przed wpadnięciem na innego rowerzystę lub pieszego – w związku z dynamiką skrętu, Rowerzysta boi się, że może kogoś nie zauważyć i spowodować kolizję. Szczególnie mocny jest strach przed wpadnięciem na innego rowerzystę, który będzie nieprzepisowo przejeżdżał przez przejście dla pieszych.
->	Strach przed byciem posądzonym o nierozważną jazdę – rowerzysta boi się, że stanie się tym, co samo go denerwuję jako pieszego.
->	Strach przed niewypowiedzianym hejtem przez innych uczestników ruchu drogowego lub pieszych – Rowerzysta stara się być lubianym i szanowanym obywatelem, w związku z tym ogarnia go strach, że stosując się lub nie do zielonej strzałki sprowadzi na siebie niewypowiedziane obelgi i złe myśli innych uczestników.
*	Strach ze względu na istnienie manewru skrętu – Rowerzysta uważa, że ze względu na niebezpieczeństwa wyżej wymienione, zielone strzałki tak jak i cały manewr skrętu powinien zostać zlikwidowany, a ruch rozwiązany inaczej aby nie stresować ludzi. 
*	Strach samej strzałki - Rowerzysta zawsze był indywidualistą, a strzałki kojarzą mu się z nakierowywaniem i przymusami. W związku z tym udział w ruchu drogowym powoduje u niego strach, gdyż niewykluczone jest, że będzie musiał podążyć za jakąś strzałką.
*	Strach koloru zielonego – Rowerzysta od zawsze ma złe skojarzenia z kolorem zielonym. W szkole podstawowej Pani od języka polskiego zawsze wystawiała mu oceny niedostateczne do dziennika takim kolorem co sprowadziło do jego niechęci na patrzenie na ten kolor. W związku z tym często odwraca od zielonych rzeczy głowę. Jednak jako uczestnik ruchu drogowego jest on zmuszony na niego patrzeć (światła, strzałka), co wywołuje u niego stres i strach, że z przyczyn od niego niezależnych przeoczy strzałkę lub jej brak.
*	Strach do przepisów – Rowerzysta do czego nie chce się przyznać, zawalił w młodości egzamin na kartę rowerową. Wykształciło to u niego lęk, przed nauką przepisów ruchu drogowego (co dodatkowo spowodowało rozwinięcie się Capiophobii oraz Testophobii), dlatego każdorazowe zetknięcie się z nim (nawet tylko poprzez zauważenie samej zielonej strzałki) wywołuję u niego niekontrolowany, paraliżujący strach.
