===== Rozwiązanie problemu strachu rowerzysty ze względu na pieszych/rowerzystów

Zalecanym rozwiązaniem dla danego problemu jest po pierwsze obniżenie prędkości (z możliwością zatrzymania się) podczas wchodzenia w skręt, aby bez problemu rozejrzeć się w sytuatcji.
Jest to najbezpieczniejsze rozwiązanie nieingerujące w jakikolwiek sposób z otoczeniem.
Kolejnym dostępnym rozwiązaniem, które jednak nie daje 100% pewności, jest wdrożenie sygnału dźwiękowego, który będzie wydawany podczas skrętu w celu ostrzeżenia innych uczestników.
Rozwiązanie to wymaga przetestowanie pod kątem rodzaju i natężenia dźwięku jaki ma być wydawany.

Trzecim z proponowanych rozwiązań, najmniej pewnym jak i najbardziej skomplikowanym, jest przeprowadzenie szeroko zakrojonej kampanii informacyjnej mającej na celu zwiększenie uwagi społeczeństwa w ruchu drogowym oraz przywiązania ich do przepisów.
Dodatkowym punktem tego rozwiązania jest przejście przez rowerzystę kursu psychologicznego w celu wyeliminowania przyczyn jego strachu.
Ostatnim rozwiązaniem jest, jak w przypadku poprzedniego rozwiązania, zaostrzenie kar -- w tym wypadku dla rowerzystów ignorujących przepisy.

Dodatkowym rozpatrywanym rozwiązaniem, które mogłoby zostać zastosowane w tym przypadku, jest przypisanie rowerzyście środków uspakajających, jednak ze względu na uczestnictwo w ruchu drogowym, jest to wysoce wzbronione.
