===== Powstawanie i uczestniczenie w korkach przy zamkniętych przejazdach

*1.* Brak tuneli lub wiaduktów kolejowych, które powodowałyby usprawnienie ruchu

`_Koszty budowy tuneli i wiaduktów oraz modernizacji istniejącej już infrastruktury drogiej jak i kolejowej_`

`_Brak wystarczającej ilości miejsca w danej okolicy (Występowanie zabudowań w okolicy przejazdów kolejowych) lub ze względu na ukształtowanie terenu._`

`_Duże utrudnia w ruchu kolejowym jak i drogowym w czasie trwania przebudowy na długi okres czasu_`

Wszystkie wypisane punkty wpływają na negatywną ocenę możliwych rozwiązań tego punktu chodź z punktu widzenia kierowców powodowałoby całkowitą eliminację występowania utrudnień z miejscach krzyżowania się ruchu kolejowego z ruchem drogowym. Ich wprowadzenie jednakże, wymagało by olbrzymich nakładów szczególności w centrach miast.

*2.* Rozwiązanie problemu niekorzystania z komunikacji miejskiej zamiast stania w korku przy zamkniętych przejazdach

`_Aby rozwiązać ten problem, można stworzyć kampanie społeczne pokazujące ludziom alternatywne sposoby i drogi komunikacji. Jednocześnie wiązałoby to się ze stworzeniem rzeczywistych możliwości, czyli zorganizowaniem przewoźników (podpisanie z nimi umów), którzy zaczęliby obsługiwać pasażerów na odcinkach zakorkowanych._`

Stworzenie możliwości alternatywnego transportu w partnerstwie publiczno-prywatnym razem z kampanią społeczną może przynieść wymiernę efekty, szczególnie jeżeli przystanki zostaną wyznaczonę w logiczny sposób a odpowiednia infrastruktura, aby nie stały one w korkach, zostanie zapewniona. Największą zachętą w tym przypadku będzie zysk czasu jaki można otrzymać z takiego rozwiązania, który po odpowiednim rozpropagowaniu, może mieć pozytywny efekt na całą kampanię. Dodakowej analizie należałoby poddać możliwości dodatkowej promocji komunikacji, zapewnienia różnych jej alternatyw (dowożenie do pociągów autobusami czy same linie autobusowe?), możliwości zmiany/przebudowy infrastruktury drogowej oraz możliwych partnerów jak i koszt całej akcji.

`_Rozwiązaniem tej sytuacji jest rozbudowa infrastruktury drogowej o dodatkowe pasy "postojowe", na których będą stały pojazdy oczekujące na otwarcie przejazdu._`

Proponowane rozwiązanie jest nistety niewykonalne w przypadku przejazdów znajdujących się w centrach miast ze względu na brak miejsca lub znaczące koszta, a proponowane rozwiązanie alternatywne nie rozwiązuje problemu braku tych pasów. Możliwe do wdrożenia na przedmieściach lub nowych dzielniacach ale wymaga dalszej analizy w celu określenia wielkości pasów, ich oznaczeniu oraz reguł prawnych jakimi miałby się rządzić. 

`_Alternatywą (choć nie tak korzystną) jest edukacja społeczeństwa i kampanie społeczne, aby nie wozić w samochodzie powietrza,_`

Podane rozwiązanie jak wcześniej wskazano nie rozwiązuję głównego problemu - braku zatoczek ale może zredukować ich zakorkowanie. Jednakże sama edukacja i kampania społeczna może nie przynieść wymiernych zysków bez połączenia jej z jakimś rozwiązaniem typu darmowy parking dla osób, które jeżdżą z pełnym samochodem. Pomysł wymaga dalszej analizy w celu zbadania możliwości przeprowadzenia kampanii, jej formatu jak i możliwych dodatkowych implikacji.

*3.* Rozwiązanie umiejscowienia przejazdów w okolicy dużych węzłów drogowych

`_przebudowanie infrastruktury kolejowej tak, aby jak najwięcej linii biegło równolegle, unikając "poszatkowania" przestrzeni miejskiej._`

Rozwiązanie to jest wyjątkowo kosztowne i często niemożliwe, ze względu na wymagania dotyczące kolei jak i już zabudowane miasta, Przebudowa w drugą stronę czyli infrastruktury drogowej powinno zostać zbadana.

`_tworzenie kolejowej obwodnicy miasta, ograniczenie wjazdu dla pociągów niepasażerskich w godzinach szczytu_`

Pomysł interesujący jednakże, wymagający analizy możliwości budowych takich obiektów jak i zbadania wpływu na zakorkowanie przejazdów oraz potencjalne zyski. W przypadku dużych miast, wydaje się także mijać z celem, gdyż rzadko chcemy mijać centra miasta pociągami pasażerskimi, a ruch cargo nie generuje znaczących kolejek w porównianiu do pasażerskiego ze względu na swoją ilości.

`_planowanie wielopoziomowych skrzyżowań drogowo-kolejowych, które nie zaburzają płynności ruchu i nie przyczyniają się do powstawania korków_`

Podane rozwiązanie jest najbardziej przyszłościowe ze wszystkich pozawalające na uniknięcie tego problemu w nowych miejscach. Powinno zostać poddane analizie projektowej i zostać dołączone przy tworzeniu nowych skrzyżowań wielopoziomowych.

`_w centrum wytyczanie torowisk pod lub nad ziemią nie tylko na skrzyżowaniach, ze względu na gęstą infrastrukturę drogową_`

Dane rozwiązanie wymagało by dużych zmian w krajobrazie, jako że torowiska nie mogą mięc zbytniego nachylenia. Co spowodowało by przeniesie większości przystanków i infrastruktury do podziemia lub nadziemia czyli zdubluowanie z metrem/koleją podwieszaną. Cały pomysł nie ma przyszłości o ile nie to nie infrasktutura drogowa będzie przenoszona.

`_płynna regulacja przejazdów na jednopoziomowych skrzyżowaniach ważnych dróg (np. ekspresowych, autostrad, obwodnic) z drogami kolejowymi poprzez analizę natężenia ruchu, a później sygnalizację maszyniście prędkości jaką powinien utrzymać by jak najlepiej dopasował się do warunków panujących na drodze. W efekcie pociągi nie mają pełnego pierwszeństwa, a jest ono regulowane przez sygnalizację._`

Rozwiązanie wymagające przeanalizowania pod względem potrzeb wprowadzonych zmian dla pojazdów szynowych i drogowych. Problemem może być estymowanie warunków, które w mieście mogą się zmienić dynamicznie bardzo ze względu na wiele czynników niezależnych tylko o ilości samochodów (wypadki i potrzeby objazdów).