===== Ocena rozwiązania dla problemu braku tuneli lub wiaduktów kolejowych
Należy zauważyć, że opis rozwiązania zawiera w sobie ocenę negatywną. W dużym stopniu, co zostało wskazane, 
jest to podyktowane kosztem inwestycji.

===== Ocena rozwiązania problemu niekorzystania z komunikacji miejskiej (jako alternatywy dla stania w korku)
Propozycja wydaje się możliwa w realizacji. Pomimo kosztów, które zostałyby poniesione (na społeczną kampanię reklamową 
oraz na realnych przewoźników, którzy świadczyliby usługi transportowe).
Istnieje jednak ryzyko, że to rozwiązanie byłoby znacznie bardziej kosztowne niż można przypuszczać. 
Warto zaznaczyć, że ten pomysł sprawdziłby się dużo lepiej, gdyby dla uczestników stworzono rozwiązanie ułatwiające dostęp 
do informacji, czyli aplikację mobilną. A taka aplikacja nie żyje w próżni, co oznacza, że musiałaby mieć stałego dostawcę, 
który by ją utrzymywał i rozwijał.

===== Ocena rozwiązania problemu braku odpowiednio długich zatoczek lub pasów dodatkowych dla osób czekających na przejazd
Zaproponowane rozwiązanie, choć ma charakter logicznej propozycji, to jednak nie uwzględnia kłopotów, które powstałyby 
w trakcie wprowadzania zmian. Przez czas trwania ewentualnego remontu i budowy dróg, komunikacja byłaby jeszcze bardziej 
utrudniona, co mogłoby doprowadzić do lokalnych demonstracji społecznych, które uniemożliwiłyby przeprowadzenie inwestycji.
Być może wybór odpowiedniego terminu na sprawne i szybkie dokonanie omawianej inwestycji, spowodowałby, że uciążliwości 
występujące w trakcie budowy, miałyby mniejszy wpływ na lokalną społeczność (tak mogłoby być w letnim sezonie wakacyjnym).
