===== Kierowcy wjeżdżają na skrzyżowania nawet jeżeli wiedzą, że nie uda im się zjechać przed zapaleniem się czerwonego światła, powodem zwykle jest nerwowość i pośpiech

*Proponowane rozwiązanie:*

Rozwiązanie dla tego problemu nie jest oczywiste ze względu na to, że źródło problemu leży zarówno po stronie społecznej jak i drogowej. Proponowane rozwiązanie zdające się rozwiązywać oba te problemy, zakładałoby wprowadzenie monitorowania skrzyżowań i ich dynamicznego rozładowywania. W miarę możliwości system powinien sprawdzać czy jakikolwiek samochód został na skrzyżowaniu i w miarę możliwości otwierać kolejny przejazd/zmieniać kolejne światło aby ten samochód mógł się schować. Ilość samochodów blokujących skrzyżowanie powinna zostać obliczona i tyle samo samochodów powinno zostać przepuszczone przez kolejne skrzyżowanie. 

Rozwiązanie to wymaga zastosowania kamer na każdym skrzyżowaniu w celu zliczania blokujących samochodów i ilości uwolnionych. Musi on być także zintegrowany z sygnalizacją/przejazdami aby móc wprowadzać konieczne zmiany. Powinien także pozwalać na ustawianie hierarchi dróg, aby nie blokować ważniejszych artieri mniejszymi skrzyżowaniami, na których ktoś zostanie na środku. Hierarchia ta także powinna w inteligentny sposób zarządzać sygnalizacją aby nie powodować większych korków (np w zamian za szybszą zmianę światła w celu uwolnienia innego skrzyżowania, wydłużenie kolejnej zmiany o ile to możliwe). 

Proponowany pomysł jednak nie dokońca rozwiązuje aspekt społeczny nerwowości (aspekt ten jest znacząco zniwelowany poprzez upłynnienie ruchu, który przełoży się na zmniejszenie nerwowości i potrzeby pośpiechu wśród kierowców jednak nie eleminiowany) i nadużywania takiego rozwiązania przez niektórych w celu osiągnięcia szybszego przejazdu.   W takim wypadku należy wprowadzić dodatkowe pomocnicze rozwiązania w postaci kar finansowych dla osób wjeżdżających na skrzyżowania bez możliwości zjazdu, powinna temu toważyszyć również kampania informacyjna, która uzmysłowi kierowcom istotę problemu. Niestety w przypadku kierowców nagminnie łapanych na blokowaniu skrzyżowań pozostaję tylko możliwość terapi.

Podane rozwiązanie jest pewną ugodą w stronę wszystkich stron zainteresowanych. Inne możliwę rozwiązania, dla których nie została przeprowadza analiza dogłębna ze względu na koszty lub/i trudność w ich wprowadzeniu to:
* Podnoszone skrzyżowania - po zmianie kierunku jazdy, całe skrzyżowanie łącznie ze znajdującymi samochodami jest wynoszone w góre na podnośnikach hydraulicznych w jego miejsce unoszone z podziemia jest drugie identyczne po którym jadą kierowcy z drugiego kierunku. 
* Dodanie dodatkowego sygnalizatora - do istniejącej instalacji sygnalizacyjnej dodanie nowej informującej o tym czy kolejny samochód zmieści się na skrzyżowaniu czy już zostanie. Instalacja taka wymagała by zmiany w przepisach (nowa sygnalizacja) jak i systemu podobnego do zastosowanego rozwiązania, jednak nie gwarantująca, że problem zostanie rozwiązany.
* Wprowadzenie pasów dla blokujących - Zamkniętę pasy przy skrzyżowaniach, które w przypadku stwierdzenia blokującego samochodu byłby automatycznie odblokowywane/otwierane, a kierowcy proszeni o jak najszybszy zjazd do nich. Byli by tam zatrzymani do kolejnej zmiany świateł. Problemem jest, że wiele skrzyżowań w centrum nie posiada miejsca na wprowadzenie takiego rozwiązania, którego wielkość musiałaby być dostosowana do wielkości takiego skrzyżowania.